linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
    packages-with-error-messages:
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
  gocritic:
    enabled-tags:
    disabled-checks:
  funlen:
    lines: 80
    statements: 80

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    #- bodyclose
    #- deadcode
    #- depguard
    #- dogsled
    #- dupl
    #- errcheck
    #- funlen
    #- gochecknoinits
    #- goconst
    #- gocritic
    #- gocyclo
    - gofmt
    - goimports
    #- golint
    #- gosec
    #- gosimple
    - govet
    #- ineffassign
    #- interfacer
    #- lll
    #- misspell
    #- nakedret
    #- scopelint
    #- staticcheck
    #- structcheck
    #- stylecheck
    #- typecheck
    #- unconvert
    #- unparam
    #- unused
    #- varcheck
    #- whitespace

  # don't enable:
  # - godox
  # - maligned,prealloc
  # - gochecknoglobals

run:
  skip-dirs:
    - testdata
  issues-exit-code: 1

service:
  golangci-lint-version: 1.19.x 
